import type { PublicSnapshot } from "./types";
const escape = (v: string) => v.replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
const label = (v: string) => escape(v.replace(/_/g, " "));
export function renderStatusPage(snapshot: PublicSnapshot): string {
  const date = (v: string) => escape(new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short", timeZone: snapshot.site.timezone }).format(new Date(v)));
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(snapshot.site.name)}</title><style>
  :root{color-scheme:light dark;font-family:system-ui,sans-serif}body{max-width:800px;margin:3rem auto;padding:0 1.5rem;line-height:1.6}h1{font-size:2rem}h2{margin-top:2rem}article,.component{border:1px solid #8885;border-radius:8px;padding:1rem;margin:.75rem 0}.component{display:flex;justify-content:space-between;gap:1rem}.operational{color:#168750}.degraded,.partial_outage{color:#ad7100}.major_outage{color:#d33}.unknown{color:#888}.status{text-transform:capitalize}time,footer{font-size:.85rem;opacity:.75}p{white-space:pre-wrap}</style></head><body>
  <header><h1>${escape(snapshot.site.name)}</h1>${snapshot.site.description ? `<p>${escape(snapshot.site.description)}</p>` : ""}<h2 class="status ${snapshot.site.status}">${label(snapshot.site.status)}</h2></header>
  <main><section aria-label="Service components">${snapshot.components.map(c => `<div class="component"><div><strong>${escape(c.name)}</strong>${c.description ? `<p>${escape(c.description)}</p>` : ""}</div><span class="status ${c.status}">${label(c.status)}</span></div>`).join("")}</section>
  <section><h2>Incidents</h2>${snapshot.incidents.length ? snapshot.incidents.map(i => `<article><h3>${escape(i.title)}</h3><span class="status">${label(i.status)} · ${label(i.impact)}</span><p><time>${date(i.started_at)}${i.resolved_at ? ` — ${date(i.resolved_at)}` : ""}</time></p>${i.updates.map(u => `<p><strong>${label(u.status)}</strong> · <time>${date(u.created_at)}</time><br>${escape(u.body)}</p>`).join("")}</article>`).join("") : "<p>No incidents reported.</p>"}</section>
  <section><h2>Maintenance</h2>${snapshot.maintenance.length ? snapshot.maintenance.map(m => `<article><h3>${escape(m.title)}</h3><span class="status">${label(m.status)}</span><p><time>${date(m.starts_at)} — ${date(m.ends_at)}</time></p><p>${escape(m.body)}</p></article>`).join("") : "<p>No maintenance scheduled.</p>"}</section></main>
  <footer>Last status change: <time>${date(snapshot.site.updated_at)}</time> (${escape(snapshot.site.timezone)})</footer></body></html>`;
}
